name: PerlToolsTeam
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  test:
    uses: tomk3003/github_workflows@use_perl_not_bash/.github/workflows/cpan-test-perl.yml@main
    with:
      perl_version: '["5.38"]'
      os: '["ubuntu-latest"]'
      testing_context: '{"MY_TEST_VAR": "MY_TEST_VALUE"}'
#
#  coverage:
#    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-coverage.yml@main
#
#  perlcritic:
#    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-perlcritic.yml@main
